server.port: 9000
spring:
  application:
    name: pneum4-board-article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/article
    username: root
    password: tjdud
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-vim: false
    show-sql: false
    hibernate:
      ddl-auto: none
